ARG CRYSTAL_VERSION=1.1.1
FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine
WORKDIR /app

# Set the commit through a build arg
ARG PLACE_COMMIT="DEV"

# - Add trusted CAs for communicating with external services
# - Add watchexec for running tests on change
RUN apk add --update --no-cache \
        bash \
        ca-certificates \
        libsodium \
        openssl \
    && \
    apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        watchexec \
    && \
    update-ca-certificates

COPY shard.yml /app
COPY shard.override.yml /app
COPY shard.lock /app

# hadolint ignore=DL3003
RUN shards install \
        --ignore-crystal-version \
        --skip-postinstall \
        --skip-executables \
    && \
    ( \
        cd lib/sodium \
        && \
        PKG_CONFIG_PATH=$(which pkg-config) \
        bash build/libsodium_install.sh \
    )

COPY scripts /app/scripts

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["/app/scripts/entrypoint.sh"]
