ARG CRYSTAL_VERSION=1.2.1
FROM placeos/service-spec-runner:${CRYSTAL_VERSION}
WORKDIR /app

# Layer libsodium and openssl (for Pulse)
RUN apk add --update --no-cache \
        libsodium-dev \
        libsodium \
        openssl

COPY shard.yml /app
COPY shard.override.yml /app
COPY shard.lock /app

# hadolint ignore=DL3003
RUN shards install \
        --ignore-crystal-version \
        --skip-postinstall \
        --skip-executables \
    && \
    ( \
        cd lib/sodium \
        && \
        PKG_CONFIG_PATH=$(which pkg-config) \
        bash build/libsodium_install.sh \
    )

ENTRYPOINT ["/app/scripts/test-entrypoint.sh"]
