version: "3.7"

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-postgresdb-client-env: &postgresdb-client-env
  PG_HOST: ${PG_HOST:-postgres}
  PG_PORT: ${PG_PORT:-5432}
  PG_DB: ${PG_DB:-place_development}
  PG_USER: ${PG_USER:-postgres}
  PG_PASSWORD: ${PG_PASSWORD:-password}

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-latest}
    volumes:
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}/lib:/app/lib
      - ${PWD}/bin:/app/bin
      - ${PWD}/shard.lock:/app/shard.lock
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml.input
      - ${PWD}/coverage:/app/coverage
    depends_on:
      - redis
      - postgres
      - migrator
    security_opt:
      - seccomp:unconfined
    environment:
      # Service Hosts
      <<: [*redis-client-env,*postgresdb-client-env,*deployment-env]
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION:-}

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ

  postgres:
    hostname: postgres
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: place_development
    ports:
      - 5432:5432

  migrator:
    build:
      context: ${PWD}/spec/migration
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      PG_DATABASE_URL: ${PG_DATABASE_URL:-postgresql://postgres:password@postgres:5432/place_development}