ARG CRYSTAL_VERSION=1.5.0
FROM placeos/service-spec-runner:${CRYSTAL_VERSION}
WORKDIR /app

# Layer libsodium and openssl (for Pulse)
RUN apk add --update --no-cache \
        openssl

COPY shard.yml /app
COPY shard.override.yml /app
COPY shard.lock /app

RUN shards install \
        --ignore-crystal-version \
        --skip-postinstall \
        --skip-executables

ENTRYPOINT ["/app/scripts/test-entrypoint.sh"]
